# Generated by Django 2.1.7 on 2022-12-10 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='user2',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
