# Generated by Django 4.1.4 on 2023-01-06 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employer',
            name='is_active',
        ),
        migrations.AddField(
            model_name='candidate',
            name='is_candidate',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='employer',
            name='is_employer',
            field=models.BooleanField(default=True),
        ),
    ]
