# Generated by Django 4.1.4 on 2023-01-09 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='applyjobs',
            field=models.TextField(default='[]'),
        ),
    ]
