# Generated by Django 4.1.4 on 2022-12-16 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StudentForm',
            new_name='CVForm',
        ),
    ]
