# Generated by Django 4.1.4 on 2023-01-09 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_candidate_applyjobs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='applyjobs',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
