# Generated by Django 4.1.4 on 2023-01-03 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_cvform_cvformmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='cvformmodel',
            name='file',
            field=models.FileField(default='files/default.pdf', upload_to='files/'),
        ),
    ]
