# Generated by Django 4.1.4 on 2023-01-06 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_employer_is_active_candidate_is_candidate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employerprofile',
            name='bio',
            field=models.TextField(blank=True, default='write you bio here...'),
        ),
    ]
