# Generated by Django 4.1.4 on 2023-01-02 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employerprofile',
            old_name='description',
            new_name='bio',
        ),
        migrations.RemoveField(
            model_name='employerprofile',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='employerprofile',
            name='photo',
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='avatar',
            field=models.ImageField(default='default.jpg', upload_to='profile_images'),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
