# Generated by Django 4.1.4 on 2023-01-06 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_employerprofile_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateprofile',
            name='bio',
            field=models.TextField(blank=True, default='write you bio here...'),
        ),
    ]
