# Generated by Django 4.1.4 on 2023-01-06 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_candidateprofile_bio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidateprofile',
            old_name='bio',
            new_name='candidate_bio',
        ),
        migrations.RenameField(
            model_name='employerprofile',
            old_name='bio',
            new_name='employer_bio',
        ),
    ]
