# Generated by Django 4.1.4 on 2023-01-06 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_bio_candidateprofile_candidate_bio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='bios',
            field=models.TextField(blank=True, default='write you bio here...'),
        ),
    ]
