# Generated by Django 4.1.3 on 2022-12-16 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='category',
            field=models.IntegerField(choices=[(1, 'Data science'), (2, 'Video game designer'), (3, 'Quality assurance engineer'), (4, 'CRM Project manager'), (5, 'Software intergration engineer'), (6, 'Data analyst'), (7, 'Full-Stack engineer')], default=1),
        ),
        migrations.AddField(
            model_name='upload',
            name='education',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='upload',
            name='hybrid',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='upload',
            name='salaryRange',
            field=models.IntegerField(choices=[(1, '0-10000'), (2, '10000-15000'), (3, '15000-30000'), (4, '30000+')], default=1),
        ),
        migrations.AddField(
            model_name='upload',
            name='time',
            field=models.IntegerField(choices=[(1, 'full time'), (2, 'part time'), (3, 'shifts')], default=1),
        ),
        migrations.AddField(
            model_name='upload',
            name='yearsexp',
            field=models.IntegerField(choices=[(1, '0-5'), (2, '5-10'), (3, '10-15'), (4, '15+')], default=1),
        ),
    ]
