# Generated by Django 4.1.3 on 2022-12-12 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='title',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
