# Generated by Django 4.1.4 on 2023-01-09 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='applycandiadteuser',
            field=models.ManyToManyField(blank=True, null=True, related_name='CandidatesCv', to='users.candidate'),
        ),
    ]
