# Generated by Django 4.1.4 on 2023-01-10 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_alter_upload_education'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
