# Generated by Django 4.1.4 on 2023-01-02 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_upload_category_upload_education_upload_hybrid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
