# Generated by Django 4.1.4 on 2023-01-09 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('jobs', '0002_alter_upload_applycandiadteuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upload',
            name='applycandiadteuser',
        ),
        migrations.AddField(
            model_name='upload',
            name='applycandiadteuser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.candidate'),
        ),
    ]
