# Generated by Django 4.1.4 on 2023-01-09 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('jobs', '0003_remove_upload_applycandiadteuser_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upload',
            name='applycandiadteuser',
        ),
        migrations.AddField(
            model_name='upload',
            name='applycandiadteuser',
            field=models.ManyToManyField(blank=True, null=True, to='users.candidate'),
        ),
    ]
