# Generated by Django 4.1.4 on 2023-01-10 23:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobs', '0003_upload_views'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upload',
            name='views',
        ),
        migrations.AddField(
            model_name='upload',
            name='views',
            field=models.ManyToManyField(blank=True, related_name='job_views', to=settings.AUTH_USER_MODEL),
        ),
    ]
