# Generated by Django 4.1.4 on 2023-01-05 12:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobs', '0003_alter_upload_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='location',
            field=models.IntegerField(choices=[(1, 'Jerusalem'), (2, 'Tel Aviv'), (3, 'Haifa'), (4, 'Rishon Le Zion'), (5, 'Beersheba')], default=1),
        ),
        migrations.AddField(
            model_name='upload',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='upload',
            name='priority',
            field=models.IntegerField(choices=[(1, 'low priority'), (2, 'mid priority'), (3, 'high priority')], default=1),
        ),
    ]
