# Generated by Django 4.1.4 on 2023-01-05 17:33

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_upload_availableamount'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='notification',
            field=models.DecimalField(decimal_places=0, default=Decimal('5'), max_digits=3),
        ),
        migrations.AlterField(
            model_name='upload',
            name='availableAmount',
            field=models.DecimalField(decimal_places=0, default=Decimal('5'), max_digits=2),
        ),
    ]
