# Generated by Django 4.1.4 on 2023-01-05 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_upload_notification_alter_upload_availableamount'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='views',
            field=models.IntegerField(default=0, unique=True),
        ),
    ]
