# Generated by Django 4.1.4 on 2023-01-11 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_alter_upload_views'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upload',
            name='views',
        ),
    ]
