# Generated by Django 4.1.4 on 2023-01-06 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_upload_views'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upload',
            name='views',
        ),
        migrations.AlterField(
            model_name='upload',
            name='priority',
            field=models.IntegerField(choices=[(1, 'high priority'), (2, 'mid priority'), (3, 'low priority')], default=1),
        ),
    ]
