# Generated by Django 4.1.4 on 2023-01-11 20:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobs', '0008_remove_upload_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='views',
            field=models.ManyToManyField(blank=True, default=0, related_name='job_views', to=settings.AUTH_USER_MODEL),
        ),
    ]
