# Generated by Django 4.1.4 on 2023-01-11 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0009_upload_views'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upload',
            name='views',
        ),
        migrations.AddField(
            model_name='upload',
            name='viewsCounter',
            field=models.IntegerField(default=0),
        ),
    ]
