# Generated by Django 4.1.4 on 2023-01-07 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tech', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='status',
            field=models.TextField(blank=True, default=' '),
        ),
    ]
