# Generated by Django 4.1.4 on 2022-12-15 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tech', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Main claim'),
        ),
    ]
