# Generated by Django 4.1.4 on 2023-01-07 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tech', '0002_ticket_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='status',
            new_name='Reply',
        ),
    ]
